#!/usr/bin/env bash
set -e
[ -n "$RENV_DEBUG" ] && set -x

# Provide Renv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec Renv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  Renv-versions --bare | while read version; do
    path="$(Renv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

RENV_COMMAND="$1"
if [ -z "$RENV_COMMAND" ]; then
  echo "usage: Renv whence [--path] COMMAND" >&2
  exit 1
fi

result="$(whence "$RENV_COMMAND")"
[ -n "$result" ] && echo "$result"
