#!/usr/bin/env bash
set -e
[ -n "$RENV_DEBUG" ] && set -x

# Provide Renv completions
if [ "$1" = "--complete" ]; then
  exec Renv shims --short
fi

RENV_COMMAND="$1"
if [ -z "$RENV_COMMAND" ]; then
  echo "usage: Renv exec COMMAND [arg1 arg2...]" >&2
  exit 1
fi

RENV_COMMAND_PATH="$(Renv-which "$RENV_COMMAND")"
RENV_BIN_PATH="${RENV_COMMAND_PATH%/*}"

for script in $(Renv-hooks exec); do
  source "$script"
done

shift 1
export PATH="${RENV_BIN_PATH}:${PATH}"
exec -a "$RENV_COMMAND" "$RENV_COMMAND_PATH" "$@"
