#!/usr/bin/env bash
set -e
[ -n "$RENV_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${RENV_ROOT}" ]; then
  RENV_ROOT="${HOME}/.Renv"
else
  RENV_ROOT="${RENV_ROOT%/}"
fi
export RENV_ROOT

if [ -z "${RENV_DIR}" ]; then
  RENV_DIR="$(pwd)"
else
  RENV_DIR="$(abs_dirname "$RENV_DIR")"
fi
export RENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${RENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${RENV_HOOK_PATH}:${RENV_ROOT}/Renv.d:/usr/local/etc/Renv.d:/etc/Renv.d"
for plugin_hook in "${RENV_ROOT}/plugins/"*/etc/Renv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export RENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "Renv 0.2.1\n$(Renv-help)" >&2
  ;;
* )
  command_path="$(command -v "Renv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "Renv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
