#!/usr/bin/env bash
set -e
[ -n "$RENV_DEBUG" ] && set -x

RENV_VERSION_NAME="$(Renv-version-name)"

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  print_version="$RENV_VERSION_NAME"
else
  hit_prefix="* "
  miss_prefix="  "
  print_version="$(Renv-version)"
fi

for path in "${RENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    version="${path##*/}"

    if [ "$version" == "$RENV_VERSION_NAME" ]; then
      echo "${hit_prefix}${print_version}"
    else
      echo "${miss_prefix}${version}"
    fi
  fi
done
