#!/usr/bin/env bash
set -e
[ -n "$RENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: Renv completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "Renv-$COMMAND" || command -v "Renv-sh-$COMMAND")"
if grep -i "^# provide Renv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
